version: '3'
services:

  # Simulation
  epanet:
    container_name: epanet
    depends_on:
      - openplc
    build:
      context: ./epanet/.
      dockerfile: Dockerfile
    volumes:
      - ./epanet/app:/app
    networks:
      - plc_network

  # Central systems
  # Vuln webserver to be placed here

  scadalts:
    container_name: scadalts
    image: scadalts/scadalts:v2.7.5.2
    environment:
      - CATALINA_OPTS=-Xmx2G -Xms2G
    ports:
      - "8081:8080" # Used for external access and debugging
    depends_on:
      - database
    expose:
      - "8080"
    volumes:
      - ./scadalts/tomcat_log:/usr/local/tomcat/logs:rw
    command:
      [
        "/usr/bin/wait-for-it",
        "--host=database",
        "--port=3306",
        "--timeout=30",
        "--strict",
        "--",
        "/usr/local/tomcat/bin/catalina.sh",
        "run"
      ]
    networks:
      - intranet
      - plc_network
      - database

  database:
    container_name: database
    image: mysql/mysql-server:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=scadalts
    expose:
      - "3306"
    volumes:
      - ./scadalts/db_data:/var/lib/mysql:rw
      - ./scadalts/db_conf:/etc/mysql:ro
    command: --log_bin_trust_function_creators=1
    networks:
      - database

  plc1:
    container_name: plc1
    depends_on:
      - scadalts
    build:
      context: ./openplc/.
      dockerfile: Dockerfile
      args:
        script: script.st
        database: slave.sh
    expose:
      - "502"
      - "8080"
    networks:
      - plc_network

  plc2:
    container_name: plc2
    depends_on:
      - scadalts
    build:
      context: ./openplc/.
      dockerfile: Dockerfile
      args:
        script: script.st
        database: slave.sh
    expose:
      - "502"
      - "8080"
    networks:
      - plc_network

  plc3:
    container_name: plc3
    depends_on:
      - scadalts
    build:
      context: ./openplc/.
      dockerfile: Dockerfile
      args:
        script: script.st
        database: slave.sh
    expose:
      - "502"
      - "8080"
    networks:
      - plc_network

  plc4:
    container_name: plc4
    depends_on:
      - scadalts
    build:
      context: ./openplc/.
      dockerfile: Dockerfile
      args:
        script: script.st
        database: slave.sh
    expose:
      - "502"
      - "8080"
    networks:
      - plc_network

  plc5:
    container_name: plc5
    depends_on:
      - scadalts
    build:
      context: ./openplc/.
      dockerfile: Dockerfile
      args:
        script: script.st
        database: slave.sh
    expose:
      - "502"
      - "8080"
    networks:
      - plc_network

  # Monitoring
  opensearch-node:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    env_file:
      - opensearch/opensearch.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - '5601'
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  intranet:
  plc_network:
  database:
  opensearch-net:
